config/routes.rb
Rails.application.routes.draw do  #match 'photos', to: 'photos#show', via: [:get, :post]
  match 'analyze/file' ,:to => 'analyze#file' ,:via => [:get,:post]
  match 'analyze/text' ,:to => 'analyze#text' ,:via => [:get,:post]
  resources :disputes
  resources :clauses

end

app/models/clause.rb
class Clause < ActiveRecord::Base
end

app/models/dispute.rb
class Dispute < ActiveRecord::Base
	has_many :claims
end

app/models/upload.rb
class Upload < ActiveRecord::Base
	has_attached_file :file
	do_not_validate_attachment_file_type :file
end

app/controllers/analyze_controller.rb
class AnalyzeController < ApplicationController
	def text
		text = params[:text]
		p text
		process1(text)
	end

	def file
		p params
		u = Upload.new(:file => params[:file])
		u.save
		text = Yomu.new(u.file.path).text
		process1(text)
	end

	def process1(text)
		sentences = text.split(/[.?!]/)
		dispute = Dispute.all.sort{ |x, y| -((x.policy_text.split(/[.?!]/) & sentences).count <=> (y.policy_text.split(/[.?!]/) & sentences).count )}[0]
		puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
		puts dispute.id
		puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
		# rendertext = disputes[0].policy_text
		clauses = Clause.where(:dispute_id => dispute.id)
		# disputes.each do |d|
		# 	cl = Clause.where(:dispute_id => d.id)[0]
		# 	if not cl.nil?
		# 		clauses << cl.clause_text
		# 	end
		# end
		writs = {
			'habeus corpus'=> 'To have a body',
			'certiorari'=> 'a writ seeking judicial review. It is issued by a superior court, directing an inferior court, tribunal, or other public authority to send the record of a proceeding for review.',
			'mandamus'=> 'Mandamus is a judicial remedy in the form of an order from a superior court, to any government subordinate court, corporation, or public authority—to do (or forbear from doing) some specific act which that body is obliged under law to do (or refrain from doing)—and which is in the nature of public duty, and in certain cases one of a statutory duty.',
			'procedendo'=> 'It is a writ that sends a case from an appellate court to a lower court with an order to proceed to judgment.',
			'writ of prohibition'=> 'A writ of prohibition is a writ directing a subordinate to stop doing something the law prohibits.',
			'quo warranto'=> 'Quo warranto (Medieval Latin for "by what warrant?") is a prerogative writ requiring the person to whom it is directed to show what authority they have for exercising some right or power (or "franchise") they claim to hold.'
		}
		puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
		clauses.each do |c|
			puts c.clause_text
			if dispute.policy_link != ''
				text = text.gsub(c.clause_text, '<a href = "'+
					dispute.policy_link+
					'" target="_blank"><mark style = "background-color:'+
					c.clause_status+'">'+
					c.clause_text+
					'</mark></a>')
				puts text
			else
				text = text.gsub(c.clause_text, '<mark style = "background-color:'+
					c.clause_status+'">'+
					c.clause_text+
					'</mark>')
				puts text
			end			
		end

		writs.keys.each do |w|
			text = text.gsub(w, 
				'<button type="button" class="btn btn-default" data-toggle="popover" data-placement="top" title="'+
				writs[w]+
				'">'+
				w+
				'</button>'

			)
		end
		puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
		# raise 'a'
		sleep(3)
		render :inline => text
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  skip_before_filter :verify_authenticity_token, :only => [:update]
end

app/controllers/clauses_controller.rb
class ClausesController < ApplicationController
  before_action :set_clause, only: [:show, :edit, :update, :destroy]

  # GET /clauses
  # GET /clauses.json
  def index
    @clauses = Clause.all
  end

  # GET /clauses/1
  # GET /clauses/1.json
  def show
  end

  # GET /clauses/new
  def new
    @clause = Clause.new
  end

  # GET /clauses/1/edit
  def edit
  end

  # POST /clauses
  # POST /clauses.json
  def create
    @clause = Clause.new(clause_params)

    respond_to do |format|
      if @clause.save
        format.html { redirect_to @clause, notice: 'Clause was successfully created.' }
        format.json { render :show, status: :created, location: @clause }
      else
        format.html { render :new }
        format.json { render json: @clause.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clauses/1
  # PATCH/PUT /clauses/1.json
  def update
    respond_to do |format|
      if @clause.update(clause_params)
        format.html { redirect_to @clause, notice: 'Clause was successfully updated.' }
        format.json { render :show, status: :ok, location: @clause }
      else
        format.html { render :edit }
        format.json { render json: @clause.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clauses/1
  # DELETE /clauses/1.json
  def destroy
    @clause.destroy
    respond_to do |format|
      format.html { redirect_to clauses_url, notice: 'Clause was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clause
      @clause = Clause.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clause_params
      params.require(:clause).permit(:dispute_id, :clause_text, :clause_status)
    end
end

app/controllers/disputes_controller.rb
class DisputesController < ApplicationController
  before_action :set_dispute, only: [:show, :edit, :update, :destroy]

  # GET /disputes
  # GET /disputes.json
  def index
    @disputes = Dispute.all
  end

  # GET /disputes/1
  # GET /disputes/1.json
  def show
  end

  # GET /disputes/new
  def new
    @dispute = Dispute.new
  end

  # GET /disputes/1/edit
  def edit
  end

  # POST /disputes
  # POST /disputes.json
  def create
    @dispute = Dispute.new(dispute_params)

    respond_to do |format|
      if @dispute.save
        format.html { redirect_to @dispute, notice: 'Dispute was successfully created.' }
        format.json { render :show, status: :created, location: @dispute }
      else
        format.html { render :new }
        format.json { render json: @dispute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disputes/1
  # PATCH/PUT /disputes/1.json
  def update
    respond_to do |format|
      if @dispute.update(dispute_params)
        format.html { redirect_to @dispute, notice: 'Dispute was successfully updated.' }
        format.json { render :show, status: :ok, location: @dispute }
      else
        format.html { render :edit }
        format.json { render json: @dispute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disputes/1
  # DELETE /disputes/1.json
  def destroy
    @dispute.destroy
    respond_to do |format|
      format.html { redirect_to disputes_url, notice: 'Dispute was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dispute
      @dispute = Dispute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dispute_params
      params.require(:dispute).permit(:company, :policy_name, :policy_text, :policy_link)
    end
end

app/helpers/analyze_helper.rb
module AnalyzeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clauses_helper.rb
module ClausesHelper
end

app/helpers/disputes_helper.rb
module DisputesHelper
end

app/views/clauses/_form.html.erb
<%= form_for(@clause) do |f| %>
  <% if @clause.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clause.errors.count, "error") %> prohibited this clause from being saved:</h2>

      <ul>
      <% @clause.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dispute_id %><br>
    <%= f.number_field :dispute_id %>
  </div>
  <div class="field">
    <%= f.label :clause_text %><br>
    <%= f.text_field :clause_text %>
  </div>
  <div class="field">
    <%= f.label :clause_status %><br>
    <%= f.text_field :clause_status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clauses/edit.html.erb
<h1>Editing clause</h1>

<%= render 'form' %>

<%= link_to 'Show', @clause %> |
<%= link_to 'Back', clauses_path %>

app/views/clauses/index.html.erb
<h1>Listing clauses</h1>

<table>
  <thead>
    <tr>
      <th>Dispute</th>
      <th>Clause text</th>
      <th>Clause status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clauses.each do |clause| %>
      <tr>
        <td><%= clause.dispute_id %></td>
        <td><%= clause.clause_text %></td>
        <td><%= clause.clause_status %></td>
        <td><%= link_to 'Show', clause %></td>
        <td><%= link_to 'Edit', edit_clause_path(clause) %></td>
        <td><%= link_to 'Destroy', clause, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Clause', new_clause_path %>

app/views/clauses/new.html.erb
<h1>New clause</h1>

<%= render 'form' %>

<%= link_to 'Back', clauses_path %>

app/views/clauses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dispute:</strong>
  <%= @clause.dispute_id %>
</p>

<p>
  <strong>Clause text:</strong>
  <%= @clause.clause_text %>
</p>

<p>
  <strong>Clause status:</strong>
  <%= @clause.clause_status %>
</p>

<%= link_to 'Edit', edit_clause_path(@clause) %> |
<%= link_to 'Back', clauses_path %>

app/views/disputes/_form.html.erb
<%= form_for(@dispute) do |f| %>
  <% if @dispute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dispute.errors.count, "error") %> prohibited this dispute from being saved:</h2>

      <ul>
      <% @dispute.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :policy_name %><br>
    <%= f.text_field :policy_name %>
  </div>
  <div class="field">
    <%= f.label :policy_text %><br>
    <%= f.text_field :policy_text %>
  </div>
  <div class="field">
    <%= f.label :policy_link %><br>
    <%= f.text_field :policy_link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/disputes/edit.html.erb
<h1>Editing dispute</h1>

<%= render 'form' %>

<%= link_to 'Show', @dispute %> |
<%= link_to 'Back', disputes_path %>

app/views/disputes/index.html.erb
<h1>Listing disputes</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Policy name</th>
      <th>Policy text</th>
      <th>Policy link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @disputes.each do |dispute| %>
      <tr>
        <td><%= dispute.company %></td>
        <td><%= dispute.policy_name %></td>
        <td><%= dispute.policy_text %></td>
        <td><%= dispute.policy_link %></td>
        <td><%= link_to 'Show', dispute %></td>
        <td><%= link_to 'Edit', edit_dispute_path(dispute) %></td>
        <td><%= link_to 'Destroy', dispute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dispute', new_dispute_path %>

app/views/disputes/new.html.erb
<h1>New dispute</h1>

<%= render 'form' %>

<%= link_to 'Back', disputes_path %>

app/views/disputes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @dispute.company %>
</p>

<p>
  <strong>Policy name:</strong>
  <%= @dispute.policy_name %>
</p>

<p>
  <strong>Policy text:</strong>
  <%= @dispute.policy_text %>
</p>

<p>
  <strong>Policy link:</strong>
  <%= @dispute.policy_link %>
</p>

<%= link_to 'Edit', edit_dispute_path(@dispute) %> |
<%= link_to 'Back', disputes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Preview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>